title: FFXIV繁中攻略
description: A FFXIV Guide
theme: just-the-docs

url: https://bk13579.github.io/ffxivguide/

aux_links:
  Github頁面: https://github.com/BK13579/ffxivguide

color_scheme: dark

aux_links_new_tab: true



collections:
  Guides:
    permalink: "/:collection/:path/"
    output: true
  Raids:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    Guides:
      name: 遊戲教學
    Raids:
      name: 高難攻略
