title: Frank太會了吧
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Github頁面: https://github.com/BK13579/ffxivguide

color_scheme: dark
