title: FFXIV繁中攻略
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://bk13579.github.io/ffxivguide/

aux_links:
  Github頁面: https://github.com/BK13579/ffxivguide

color_scheme: dark
